dojo.provide("dojo.nls.dojo_ja-jp");
dojo.provide("dijit.form.nls.validate");
dijit.form.nls.validate._built = true;
dojo.provide("dijit.form.nls.validate.ja_jp");
dijit.form.nls.validate.ja_jp = {"rangeMessage": "この値は範囲外です。", "invalidMessage": "入力した値は無効です。", "missingMessage": "この値は必須です。"};
dojo.provide("dojo.cldr.nls.number");
dojo.cldr.nls.number._built = true;
dojo.provide("dojo.cldr.nls.number.ja_jp");
dojo.cldr.nls.number.ja_jp = {"currencyFormat": "¤#,##0.00", "decimalFormat": "#,##0.###", "group": ",", "scientificFormat": "#E0", "percentFormat": "#,##0%", "decimal": ".", "currencySpacing-afterCurrency-currencyMatch": "[:letter:]", "infinity": "∞", "list": ";", "percentSign": "%", "minusSign": "-", "currencySpacing-beforeCurrency-surroundingMatch": "[:digit:]", "currencySpacing-afterCurrency-insertBetween": " ", "nan": "NaN", "nativeZeroDigit": "0", "plusSign": "+", "currencySpacing-afterCurrency-surroundingMatch": "[:digit:]", "currencySpacing-beforeCurrency-currencyMatch": "[:letter:]", "perMille": "‰", "patternDigit": "#", "currencySpacing-beforeCurrency-insertBetween": " ", "exponential": "E"};
dojo.provide("dojo.cldr.nls.gregorian");
dojo.cldr.nls.gregorian._built = true;
dojo.provide("dojo.cldr.nls.gregorian.ja_jp");
dojo.cldr.nls.gregorian.ja_jp = {"field-dayperiod": "午前/午後", "field-minute": "分", "eraNames": ["紀元前", "西暦"], "field-weekday": "曜日", "days-standAlone-wide": ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"], "months-standAlone-narrow": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], "field-era": "時代", "field-hour": "時", "timeFormat-full": "H時mm分ss秒v", "months-standAlone-abbr": ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"], "days-standAlone-narrow": ["日", "月", "火", "水", "木", "金", "土"], "eraAbbr": ["紀元前", "西暦"], "dateFormat-long": "yyyy年M月d日", "timeFormat-medium": "H:mm:ss", "field-zone": "タイムゾーン", "dateFormat-medium": "yyyy/MM/dd", "quarters-standAlone-wide": ["第1四半期", "第2四半期", "第3四半期", "第4四半期"], "dateTimeFormat": "{1} {0}", "field-year": "年", "quarters-standAlone-narrow": ["1", "2", "3", "4"], "months-standAlone-wide": ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"], "field-week": "週", "timeFormat-long": "HH:mm:ssz", "months-format-abbr": ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"], "timeFormat-short": "H:mm", "field-month": "月", "quarters-format-abbr": ["Q1", "Q2", "Q3", "Q4"], "days-format-abbr": ["日", "月", "火", "水", "木", "金", "土"], "pm": "午後", "days-format-narrow": ["日", "月", "火", "水", "木", "金", "土"], "field-second": "秒", "field-day": "日", "am": "午前", "days-standAlone-abbr": ["日", "月", "火", "水", "木", "金", "土"], "dateFormat-short": "yy/MM/dd", "dateFormat-full": "yyyy年M月d日EEEE", "months-format-wide": ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"], "dateTimeAvailableFormats": ["d日(EEE)", "GGGGy年M月d日", "H時", "H:mm", "L", "M/d(E)", "LLL", "M月d日(E)", "M月d日(E)", "M月d日", "M月d日", "MM/dd", "M/d", "d日", "mm:ss", "mm:ss", "y", "y/M", "y/M/d(EEE)", "y年M月", "y年M月d日(EEE)", "y年M月", "y/Q", "yyyyQQQ", "y年M月", "yy/Q", "y年", "yyyy/MM"], "quarters-format-wide": ["第1四半期", "第2四半期", "第3四半期", "第4四半期"], "days-format-wide": ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"], "eraNarrow": ["紀元前", "西暦"], "dateTimeFormats-appendItem-Second": "{0} ({2}: {1})", "dateTimeFormats-appendItem-Year": "{0} {1}", "quarters-standAlone-abbr": ["Q1", "Q2", "Q3", "Q4"], "dateTimeFormats-appendItem-Week": "{0} ({2}: {1})", "dateTimeFormats-appendItem-Timezone": "{0} {1}", "dateTimeFormats-appendItem-Month": "{0} ({2}: {1})", "dateTimeFormats-appendItem-Minute": "{0} ({2}: {1})", "dateTimeFormats-appendItem-Day": "{0} ({2}: {1})", "quarters-format-narrow": ["1", "2", "3", "4"], "dateTimeFormats-appendItem-Quarter": "{0} ({2}: {1})", "dateTimeFormats-appendItem-Day-Of-Week": "{0} {1}", "months-format-narrow": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], "dateTimeFormats-appendItem-Hour": "{0} ({2}: {1})", "dateTimeFormats-appendItem-Era": "{0} {1}"};
dojo.provide("dojo.cldr.nls.currency");
dojo.cldr.nls.currency._built = true;
dojo.provide("dojo.cldr.nls.currency.ja_jp");
dojo.cldr.nls.currency.ja_jp = {"HKD_displayName": "香港ドル", "CHF_displayName": "スイス フラン", "JPY_symbol": "￥", "CAD_displayName": "カナダ ドル", "CNY_displayName": "中国人民元", "AUD_displayName": "オーストラリア ドル", "JPY_displayName": "日本円", "USD_displayName": "米ドル", "CNY_symbol": "元", "GBP_displayName": "英国ポンド", "EUR_displayName": "ユーロ", "USD_symbol": "US$", "GBP_symbol": "UK£", "EUR_symbol": "€"};
dojo.provide("dijit.nls.loading");
dijit.nls.loading._built = true;
dojo.provide("dijit.nls.loading.ja_jp");
dijit.nls.loading.ja_jp = {"loadingState": "ロード中...", "errorState": "エラーが発生しました。"};
dojo.provide("dijit.nls.common");
dijit.nls.common._built = true;
dojo.provide("dijit.nls.common.ja_jp");
dijit.nls.common.ja_jp = {"buttonOk": "OK", "buttonCancel": "キャンセル", "buttonSave": "保存", "itemClose": "閉じる"};
