dojo.provide("dojo.nls.dojo_el");
dojo.provide("dijit.form.nls.validate");
dijit.form.nls.validate._built = true;
dojo.provide("dijit.form.nls.validate.el");
dijit.form.nls.validate.el = {"rangeMessage": "Η τιμή αυτή δεν ανήκει στο εύρος έγκυρων τιμών.", "invalidMessage": "Η τιμή που καταχωρήσατε δεν είναι έγκυρη.", "missingMessage": "Η τιμή αυτή πρέπει απαραίτητα να καθοριστεί."};
dojo.provide("dojo.cldr.nls.number");
dojo.cldr.nls.number._built = true;
dojo.provide("dojo.cldr.nls.number.el");
dojo.cldr.nls.number.el = {"scientificFormat": "#E0", "currencySpacing-afterCurrency-currencyMatch": "[:letter:]", "infinity": "∞", "list": ";", "percentSign": "%", "minusSign": "-", "currencySpacing-beforeCurrency-surroundingMatch": "[:digit:]", "currencySpacing-afterCurrency-insertBetween": " ", "nan": "NaN", "nativeZeroDigit": "0", "plusSign": "+", "currencySpacing-afterCurrency-surroundingMatch": "[:digit:]", "currencyFormat": "¤ #,##0.00", "currencySpacing-beforeCurrency-currencyMatch": "[:letter:]", "perMille": "‰", "group": ",", "percentFormat": "#,##0%", "decimalFormat": "#,##0.###", "decimal": ".", "patternDigit": "#", "currencySpacing-beforeCurrency-insertBetween": " ", "exponential": "E"};
dojo.provide("dojo.cldr.nls.gregorian");
dojo.cldr.nls.gregorian._built = true;
dojo.provide("dojo.cldr.nls.gregorian.el");
dojo.cldr.nls.gregorian.el = {"dateTimeFormats-appendItem-Second": "{0} ({2}: {1})", "field-dayperiod": "Dayperiod", "field-minute": "Minute", "eraNames": ["BCE", "CE"], "field-weekday": "Day of the Week", "days-standAlone-wide": ["1", "2", "3", "4", "5", "6", "7"], "months-standAlone-narrow": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], "dateTimeFormats-appendItem-Year": "{0} {1}", "field-era": "Era", "field-hour": "Hour", "quarters-standAlone-abbr": ["Q1", "Q2", "Q3", "Q4"], "timeFormat-full": "HH:mm:ss v", "dateTimeFormats-appendItem-Week": "{0} ({2}: {1})", "dateTimeFormats-appendItem-Timezone": "{0} {1}", "months-standAlone-abbr": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], "dateTimeFormats-appendItem-Month": "{0} ({2}: {1})", "days-standAlone-narrow": ["1", "2", "3", "4", "5", "6", "7"], "eraAbbr": ["BCE", "CE"], "dateFormat-long": "yyyy MMMM d", "timeFormat-medium": "HH:mm:ss", "field-zone": "Zone", "dateTimeFormats-appendItem-Minute": "{0} ({2}: {1})", "dateFormat-medium": "yyyy MMM d", "quarters-standAlone-wide": ["Q1", "Q2", "Q3", "Q4"], "dateTimeFormat": "{1} {0}", "field-year": "Year", "quarters-standAlone-narrow": ["1", "2", "3", "4"], "months-standAlone-wide": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], "dateTimeFormats-appendItem-Day": "{0} ({2}: {1})", "field-week": "Week", "quarters-format-narrow": ["1", "2", "3", "4"], "timeFormat-long": "HH:mm:ss z", "months-format-abbr": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], "timeFormat-short": "HH:mm", "field-month": "Month", "dateTimeFormats-appendItem-Quarter": "{0} ({2}: {1})", "quarters-format-abbr": ["Q1", "Q2", "Q3", "Q4"], "days-format-abbr": ["1", "2", "3", "4", "5", "6", "7"], "pm": "PM", "days-format-narrow": ["1", "2", "3", "4", "5", "6", "7"], "field-second": "Second", "field-day": "Day", "dateTimeFormats-appendItem-Day-Of-Week": "{0} {1}", "months-format-narrow": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], "dateTimeFormats-appendItem-Hour": "{0} ({2}: {1})", "am": "AM", "days-standAlone-abbr": ["1", "2", "3", "4", "5", "6", "7"], "dateFormat-short": "yyyy-MM-dd", "dateFormat-full": "EEEE, yyyy MMMM dd", "months-format-wide": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], "dateTimeAvailableFormats": ["H:mm", "L", "E, M-d", "LLL", "E MMM d", "E MMMM d", "MMMM d", "MMM d", "M-d", "d", "mm:ss", "yyyy", "yyyy-M", "EEE, yyyy-M-d", "yyyy MMM", "EEE, yyyy MMM d", "yyyy MMMM", "yyyy Q", "yyyy QQQ"], "dateTimeFormats-appendItem-Era": "{0} {1}", "quarters-format-wide": ["Q1", "Q2", "Q3", "Q4"], "eraNarrow": ["BCE", "CE"], "days-format-wide": ["1", "2", "3", "4", "5", "6", "7"]};
dojo.provide("dojo.cldr.nls.currency");
dojo.cldr.nls.currency._built = true;
dojo.provide("dojo.cldr.nls.currency.el");
dojo.cldr.nls.currency.el = {"USD_symbol": "US$", "EUR_displayName": "EUR", "GBP_displayName": "GBP", "JPY_displayName": "JPY", "GBP_symbol": "UK£", "JPY_symbol": "JP¥", "EUR_symbol": "€", "USD_displayName": "USD"};
dojo.provide("dijit.nls.loading");
dijit.nls.loading._built = true;
dojo.provide("dijit.nls.loading.el");
dijit.nls.loading.el = {"loadingState": "Φόρτωση...", "errorState": "Σας ζητούμε συγνώμη, παρουσιάστηκε σφάλμα"};
dojo.provide("dijit.nls.common");
dijit.nls.common._built = true;
dojo.provide("dijit.nls.common.el");
dijit.nls.common.el = {"buttonOk": "OK", "buttonCancel": "Ακύρωση", "buttonSave": "Αποθήκευση", "itemClose": "Κλείσιμο"};
