spring:
  datasource:
    url: jdbc:h2:mem:shivtest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: warn
