apiVersion: v2
name: todo-backend-chart
description: A Helm chart to deploy a JBoss EAP todo-backend application and its Postgresql database
type: application
version: 1.0.0
dependencies:
    - name: eap82
      repository: https://jbossas.github.io/eap-charts/
      version: 1.0.0
