CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(12) NOT NULL
);

INSERT INTO member (name, email, phone_number) VALUES
    ('John Smith', 'john.smith@mailinator.com', '2125551212');
